<?php
/**
 * Setup Wizard
 * Run once to configure the bot
 * Delete or protect this file after setup!
 */

declare(strict_types=1);

require_once __DIR__ . '/src/autoload.php';

use SolanaAgent\Utils\Crypto;

$configFile = __DIR__ . '/config/config.php';
$step       = (int)($_GET['step'] ?? 1);
$message    = '';
$error      = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';

    if ($action === 'save_config') {
        try {
            // Read current config
            $config = require $configFile;

            // Update values
            $config['telegram']['bot_token']       = trim($_POST['bot_token'] ?? '');
            $config['telegram']['webhook_secret']  = trim($_POST['webhook_secret'] ?? '');
            $config['ai']['groq']['api_key']        = trim($_POST['groq_key'] ?? '');
            $config['ai']['gemini']['api_key']      = trim($_POST['gemini_key'] ?? '');
            $config['ai']['cohere']['api_key']      = trim($_POST['cohere_key'] ?? '');
            $config['ai']['primary']                = trim($_POST['ai_primary'] ?? 'groq');
            $config['solana']['network']            = trim($_POST['network'] ?? 'devnet');
            $config['app']['base_url']              = rtrim(trim($_POST['base_url'] ?? ''), '/');

            $encKey = trim($_POST['encryption_key'] ?? '');
            if (strlen($encKey) < 16) {
                throw new \RuntimeException('Encryption key must be at least 16 characters.');
            }
            $config['security']['encryption_key'] = $encKey;

            $adminPass = trim($_POST['admin_password'] ?? '');
            if (strlen($adminPass) < 6) {
                throw new \RuntimeException('Admin password must be at least 6 characters.');
            }
            $config['security']['admin_password'] = Crypto::hashPassword($adminPass);
            $config['security']['admin_username']  = trim($_POST['admin_username'] ?? 'admin');
            $config['security']['cron_secret']     = Crypto::randomToken(16);
            $config['apis']['helius_key']          = trim($_POST['helius_key'] ?? '');

            // Write config
            $configContent = "<?php\n/** Auto-generated by setup.php - Edit carefully! */\n\n"
                . "define('ROOT_PATH',   __DIR__ . '/..');\n"
                . "define('DATA_PATH',   ROOT_PATH . '/data');\n"
                . "define('LOG_PATH',    DATA_PATH . '/logs');\n"
                . "define('WALLET_PATH', DATA_PATH . '/wallets');\n"
                . "define('SRC_PATH',    ROOT_PATH . '/src');\n\n"
                . "return " . var_export($config, true) . ";\n";

            file_put_contents($configFile, $configContent);

            // Initialize database
            $db = \SolanaAgent\Storage\Database::getInstance($config['database']['file']);

            // Create directories
            foreach ([DATA_PATH ?? __DIR__ . '/data', LOG_PATH ?? __DIR__ . '/data/logs'] as $dir) {
                if (!is_dir($dir)) mkdir($dir, 0755, true);
            }

            $message = 'Configuration saved successfully!';
            $step = 3;

        } catch (\Throwable $e) {
            $error = $e->getMessage();
        }
    }
}

// Check PHP extensions
$checks = [
    'PHP 7.4+' => version_compare(PHP_VERSION, '7.4.0', '>='),
    'sodium'   => extension_loaded('sodium'),
    'PDO'      => class_exists('PDO'),
    'pdo_sqlite'=> in_array('sqlite', \PDO::getAvailableDrivers()),
    'openssl'  => extension_loaded('openssl'),
    'curl'     => extension_loaded('curl'),
    'simplexml'=> extension_loaded('simplexml'),
    'gmp'      => extension_loaded('gmp'),
];
$allOk = !in_array(false, $checks, true);

?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Setup — Solana Agent Bot</title>
<link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
<link href="assets/css/style.css" rel="stylesheet">
</head>
<body class="auth">
<div class="setup-wrap">
  <div class="setup-card">
    <div class="login-brand">
      <div class="logo-hex">◈</div>
      <h1>Solana<span class="accent">Agent</span> Setup</h1>
      <p>Step <?= $step ?> of 3</p>
    </div>

    <?php if ($message): ?><div class="alert alert-success"><?= htmlspecialchars($message) ?></div><?php endif ?>
    <?php if ($error): ?><div class="alert alert-error"><?= htmlspecialchars($error) ?></div><?php endif ?>

    <?php if ($step === 1): ?>
    <!-- Step 1: System check -->
    <h3 class="setup-section">System Requirements</h3>
    <div class="checks">
      <?php foreach ($checks as $ext => $ok): ?>
      <div class="check-item <?= $ok ? 'ok' : 'fail' ?>">
        <span class="check-icon"><?= $ok ? '✅' : '❌' ?></span>
        <span><?= $ext ?></span>
      </div>
      <?php endforeach ?>
    </div>

    <?php if (!$allOk): ?>
    <div class="alert alert-error">
      Some requirements are missing. Install the required PHP extensions and refresh.
    </div>
    <?php else: ?>
    <a href="?step=2" class="btn btn-primary btn-full">Continue →</a>
    <?php endif ?>

    <?php elseif ($step === 2): ?>
    <!-- Step 2: Configuration -->
    <form method="POST" action="?step=2">
      <input type="hidden" name="action" value="save_config">

      <h3 class="setup-section">🤖 Telegram</h3>
      <div class="field">
        <label>Bot Token <span class="req">*</span></label>
        <input type="text" name="bot_token" placeholder="1234567890:AAF..." required>
        <small>Get from <a href="https://t.me/BotFather" target="_blank">@BotFather</a></small>
      </div>
      <div class="field">
        <label>Webhook Secret (optional)</label>
        <input type="text" name="webhook_secret" placeholder="random_secret_string">
      </div>
      <div class="field">
        <label>Your Site Base URL <span class="req">*</span></label>
        <input type="url" name="base_url" placeholder="https://yourdomain.com" required>
      </div>

      <h3 class="setup-section">🧠 AI APIs (free tiers)</h3>
      <div class="field">
        <label>Primary AI Provider</label>
        <select name="ai_primary">
          <option value="groq">Groq (fastest — recommended)</option>
          <option value="gemini">Google Gemini</option>
          <option value="cohere">Cohere</option>
        </select>
      </div>
      <div class="field">
        <label>Groq API Key</label>
        <input type="text" name="groq_key" placeholder="gsk_...">
        <small><a href="https://console.groq.com" target="_blank">Get free key at console.groq.com</a></small>
      </div>
      <div class="field">
        <label>Google Gemini API Key</label>
        <input type="text" name="gemini_key" placeholder="AIza...">
        <small><a href="https://aistudio.google.com" target="_blank">Get free key at aistudio.google.com</a></small>
      </div>
      <div class="field">
        <label>Cohere API Key (optional)</label>
        <input type="text" name="cohere_key" placeholder="...">
        <small><a href="https://dashboard.cohere.com" target="_blank">dashboard.cohere.com</a></small>
      </div>

      <h3 class="setup-section">⛓️ Solana</h3>
      <div class="field">
        <label>Network</label>
        <select name="network">
          <option value="devnet" selected>Devnet (testing)</option>
          <option value="mainnet">Mainnet (production)</option>
        </select>
      </div>
      <div class="field">
        <label>Helius API Key (optional)</label>
        <input type="text" name="helius_key" placeholder="...">
        <small><a href="https://dev.helius.xyz" target="_blank">100k free req/day at helius.xyz</a></small>
      </div>

      <h3 class="setup-section">🔐 Security</h3>
      <div class="field">
        <label>Encryption Key <span class="req">*</span></label>
        <input type="text" name="encryption_key"
          value="<?= bin2hex(random_bytes(16)) ?>"
          minlength="16" required>
        <small>Used to encrypt private keys. NEVER change this after wallets are created!</small>
      </div>
      <div class="field">
        <label>Admin Username <span class="req">*</span></label>
        <input type="text" name="admin_username" value="admin" required>
      </div>
      <div class="field">
        <label>Admin Password <span class="req">*</span></label>
        <input type="password" name="admin_password" minlength="6" required>
      </div>

      <button type="submit" class="btn btn-primary btn-full">Save & Initialize →</button>
    </form>

    <?php elseif ($step === 3): ?>
    <!-- Step 3: Done -->
    <div class="success-screen">
      <div class="success-icon">✅</div>
      <h3>Setup Complete!</h3>
      <p>Your Solana Agent Bot is configured and ready.</p>

      <div class="next-steps">
        <h4>Next Steps:</h4>
        <ol>
          <li>Go to <a href="index.php?page=settings">Admin Settings</a> and set your webhook URL</li>
          <li>Set up cron: <code>* * * * * php <?= realpath(__DIR__) ?>/cron.php</code></li>
          <li>Test your bot on Telegram — send /start</li>
          <li>⚠️ <strong>Delete or protect setup.php from public access!</strong></li>
        </ol>
      </div>

      <a href="index.php" class="btn btn-primary btn-full">Go to Admin Panel →</a>
    </div>
    <?php endif ?>
  </div>
</div>
</body>
</html>
