<?php
/** Auto-generated by setup.php - Edit carefully! */

define('ROOT_PATH',   __DIR__ . '/..');
define('DATA_PATH',   ROOT_PATH . '/data');
define('LOG_PATH',    DATA_PATH . '/logs');
define('WALLET_PATH', DATA_PATH . '/wallets');
define('SRC_PATH',    ROOT_PATH . '/src');

return array (
  'app' => 
  array (
    'name' => 'Solana Agent Bot',
    'version' => '1.0.0',
    'debug' => false,
    'timezone' => 'Africa/Lagos',
    'base_url' => 'https://solanaagent.earnton.online',
  ),
  'telegram' => 
  array (
    'bot_token' => '8619723776:AAGMU6j08-4BTDDUzQZZWyn1RkJ5REVdK3A',
    'webhook_secret' => '',
    'parse_mode' => 'HTML',
  ),
  'ai' => 
  array (
    'primary' => 'groq',
    'fallback' => 'gemini',
    'groq' => 
    array (
      'api_key' => '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',
      'model' => 'llama-3.3-70b-versatile',
      'endpoint' => 'https://api.groq.com/openai/v1/chat/completions',
      'max_tokens' => 1024,
    ),
    'gemini' => 
    array (
      'api_key' => 'AIzaSyAiF4z3vDCrD36DGAmTjsUtS0k_GCPDROc',
      'model' => 'gemini-2.0-flash-lite',
      'endpoint' => 'https://generativelanguage.googleapis.com/v1beta/models/',
      'max_tokens' => 1024,
    ),
    'cohere' => 
    array (
      'api_key' => 'gD24O45hxW0bfoO9CfvYCtgRvKuIZ4sCDsUVGTl0',
      'model' => 'command-r',
      'endpoint' => 'https://api.cohere.ai/v1/chat',
      'max_tokens' => 1024,
    ),
  ),
  'solana' => 
  array (
    'rpc_mainnet' => 'https://api.mainnet-beta.solana.com',
    'rpc_devnet' => 'https://api.devnet.solana.com',
    'network' => 'devnet',
    'explorer' => 'https://explorer.solana.com',
    'commitment' => 'confirmed',
  ),
  'security' => 
  array (
    'encryption_key' => '3ea74d2abe0782425d6df7ede01a6381',
    'admin_username' => 'admin',
    'admin_password' => '$2y$12$qgV76LYaQ7SLQRhUt2L7uOtfbbMsWS82osALwBU2ojTVDembRzaem',
    'session_lifetime' => 3600,
    'jwt_secret' => '',
    'cron_secret' => 'af00d6df2ff0aeacbec52830b07af6a6',
  ),
  'database' => 
  array (
    'file' => '/home/earnhuun/solanaagent.earnton.online/config/../data/agent.db',
  ),
  'apis' => 
  array (
    'coingecko' => 'https://api.coingecko.com/api/v3',
    'magic_eden' => 'https://api-mainnet.magiceden.dev/v2',
    'news_rss' => 'https://cointelegraph.com/rss/tag/solana',
    'helius_key' => 'be723158-0b81-42a4-9939-dd523488bd17',
    'helius_rpc' => 'https://mainnet.helius-rpc.com',
    'sns_api' => 'https://sns-sdk-proxy.bonfida.workers.dev',
  ),
  'features' => 
  array (
    'price_alert_interval' => 60,
    'scheduled_task_interval' => 30,
    'max_wallets_per_user' => 5,
    'languages' => 
    array (
      0 => 'english',
      1 => 'yoruba',
      2 => 'igbo',
      3 => 'hausa',
      4 => 'pidgin',
    ),
  ),
);
